/*
 * This file is responsible for the UI of input system.
 * Created on: 14-10-2020
 * Last Modified on: 01-11-2020
 * Author: Shah Axat(19IT126)
 */

package Wordoku;

import javax.swing.*;

public class InputUI<a> extends javax.swing.JPanel {
    private WordokuUI board;
    private JPanel block;
    private JButton inputButton;
    private int numberOfInput;
    char a[] = Wordoku.toBeFilled;
    //Creates new form InputUI

    public InputUI(WordokuUI board, JPanel block, JButton inButton, int numberOfInput) {
        this.board = board;
        this.block = block;
        this.inputButton = inButton;
        this.numberOfInput = numberOfInput;
        initComponents();

     /*   //For 6x6
        if (numberOfInput < 7) {
            this.remove(seven);
            this.remove(eight);
            this.remove(nine);
        }*/
    }

    /*
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        //Create a copy of array to use for inputs

        one = new javax.swing.JButton();
        two = new javax.swing.JButton();
        three = new javax.swing.JButton();
        four = new javax.swing.JButton();
        five = new javax.swing.JButton();
        six = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        nine = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(3, 3));

        one.setBackground(new java.awt.Color(255, 255, 255));
        one.setText(String.valueOf(a[0]));
        one.setAlignmentY(0.0F);
        one.setIconTextGap(1);
        one.setMargin(new java.awt.Insets(2, 2, 2, 2));
        one.setMinimumSize(new java.awt.Dimension(15, 15));
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setAns(evt);
            }
        });
        add(one);

        two.setBackground(new java.awt.Color(255, 255, 255));
        two.setText(String.valueOf(a[1]));
        two.setAlignmentY(0.0F);
        two.setIconTextGap(1);
        two.setMargin(new java.awt.Insets(2, 2, 2, 2));
        two.setMinimumSize(new java.awt.Dimension(15, 15));
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setAns(evt);
            }
        });
        add(two);

        three.setBackground(new java.awt.Color(255, 255, 255));
        three.setText(String.valueOf(a[2]));
        three.setAlignmentY(0.0F);
        three.setIconTextGap(1);
        three.setMargin(new java.awt.Insets(2, 2, 2, 2));
        three.setMinimumSize(new java.awt.Dimension(15, 15));
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setAns(evt);
            }
        });
        add(three);

        four.setBackground(new java.awt.Color(255, 255, 255));
        four.setText(String.valueOf(a[3]));
        four.setAlignmentY(0.0F);
        four.setIconTextGap(1);
        four.setMargin(new java.awt.Insets(2, 2, 2, 2));
        four.setMinimumSize(new java.awt.Dimension(15, 15));
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setAns(evt);
            }
        });
        add(four);

        five.setBackground(new java.awt.Color(255, 255, 255));
        five.setText(String.valueOf(a[4]));
        five.setAlignmentY(0.0F);
        five.setIconTextGap(1);
        five.setMargin(new java.awt.Insets(2, 2, 2, 2));
        five.setMinimumSize(new java.awt.Dimension(15, 15));
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setAns(evt);
            }
        });
        add(five);

        six.setBackground(new java.awt.Color(255, 255, 255));
        six.setText(String.valueOf(a[5]));
        six.setAlignmentY(0.0F);
        six.setIconTextGap(1);
        six.setMargin(new java.awt.Insets(2, 2, 2, 2));
        six.setMinimumSize(new java.awt.Dimension(15, 15));
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setAns(evt);
            }
        });
        add(six);

        if (numberOfInput > 6) {
            seven.setBackground(new java.awt.Color(255, 255, 255));
            seven.setText(String.valueOf(a[6]));
            seven.setAlignmentY(0.0F);
            seven.setIconTextGap(1);
            seven.setMargin(new java.awt.Insets(2, 2, 2, 2));
            seven.setMinimumSize(new java.awt.Dimension(15, 15));
            seven.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    setAns(evt);
                }
            });
            add(seven);

            eight.setBackground(new java.awt.Color(255, 255, 255));
            eight.setText(String.valueOf(a[7]));
            eight.setAlignmentY(0.0F);
            eight.setIconTextGap(1);
            eight.setMargin(new java.awt.Insets(2, 2, 2, 2));
            eight.setMinimumSize(new java.awt.Dimension(15, 15));
            eight.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    setAns(evt);
                }
            });
            add(eight);

            nine.setBackground(new java.awt.Color(255, 255, 255));
            nine.setText(String.valueOf(a[8]));
            nine.setAlignmentY(0.0F);
            nine.setIconTextGap(1);
            nine.setMargin(new java.awt.Insets(2, 2, 2, 2));
            nine.setMinimumSize(new java.awt.Dimension(15, 15));
            nine.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    setAns(evt);
                }
            });
            add(nine);
        }
    }// </editor-fold>

    private void setAns(java.awt.event.ActionEvent evt) {
        board.setInput(evt.getActionCommand(), block, inputButton);
    }


    // Variable declaration- Never Modify this
    private javax.swing.JButton eight;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JButton nine;
    private javax.swing.JButton one;
    private javax.swing.JButton seven;
    private javax.swing.JButton six;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    // End of variables declaration
}
